name = "spirospares"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[env.production]
name = "spirospares-production"
routes = [
  { pattern = "spirospares.com", zone_name = "spirospares.com" }
]
