export const starterDocuments = [
  {
    _id: 'siteSettings',
    _type: 'siteSettings',
    siteName: 'SPIRO SPARES',
    siteDescription:
      'Genuine Spiro EV spares, bikes, gadgets, and service support across Nairobi and Kenya.',
    contactEmail: 'info@spirospares.com',
    contactPhone: '+254733959383',
    whatsappNumber: '+254733959383',
    address:
      'Dunga Close, Near Car & General Roundabout, Industrial Area, Nairobi, Kenya',
    businessHours: 'Mon-Sat: 8AM-6PM',
    socialLinks: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com',
      linkedin: 'https://linkedin.com',
    },
  },
  {
    _id: 'category-bikes',
    _type: 'category',
    name: 'Bikes',
    slug: {current: 'bikes'},
    type: 'bike',
    description: 'Electric bike models available for riders and fleets.',
  },
  {
    _id: 'category-spares',
    _type: 'category',
    name: 'Spares',
    slug: {current: 'spares'},
    type: 'sparePart',
    description: 'Genuine spare parts and replacement components.',
  },
  {
    _id: 'bike-veo',
    _type: 'bike',
    name: 'VEO',
    category: {_type: 'reference', _ref: 'category-bikes'},
    price: 199500,
    sku: 'SPI-VEO-002',
    shortDescription:
      'Compact and efficient for city commuting with quick battery swapping support.',
    stock: 24,
    motor: '3.5kW Peak',
    range: '95 km',
    battery: '60V 40Ah Swappable',
    speed: '70 km/h',
    chargingTime: '3 hours',
    isActive: true,
  },
  {
    _id: 'bike-commando',
    _type: 'bike',
    name: 'COMMANDO',
    category: {_type: 'reference', _ref: 'category-bikes'},
    price: 245000,
    sku: 'SPI-COM-001',
    shortDescription:
      'Built for heavy-duty delivery routes with strong uptime and fleet support.',
    stock: 18,
    motor: '5.0kW Peak',
    range: '110 km',
    battery: '72V 45Ah Swappable',
    speed: '85 km/h',
    chargingTime: '3.5 hours',
    isActive: true,
  },
  {
    _id: 'spare-drive-chain',
    _type: 'sparePart',
    name: 'Drive Chain (Complete Loop)',
    partCode: 'SP-DRC-001',
    price: 5400,
    category: 'General',
    compatibleModels: [
      {_type: 'reference', _ref: 'bike-veo'},
      {_type: 'reference', _ref: 'bike-commando'},
    ],
    function: 'Transfers motor torque to the rear wheel for smooth acceleration.',
    replacementCycle: 'Inspect every 4,000 km; replace every 15,000-20,000 km.',
    stock: 46,
    material: 'Heat-treated alloy steel',
    quality: 'OEM fitment with anti-rust coating',
    isActive: true,
  },
  {
    _id: 'gadget-phone-holder',
    _type: 'gadget',
    name: 'Smart Quad Phone Holder',
    price: 4500,
    features: ['Anti-vibration mount', 'One-twist locking', 'Rain-resistant shell'],
    compatibility: 'Compatible with all Spiro platforms',
    category: 'Phone holders',
    technicalDetails: '360-degree swivel, impact-rated mount, 4-point anchor',
    stock: 50,
    isActive: true,
  },
  {
    _id: 'service-nairobi-cbd',
    _type: 'serviceLocation',
    name: 'Nairobi CBD Service Center',
    city: 'Nairobi',
    area: 'CBD',
    address: 'Industrial Area, Nairobi, Kenya',
    phone: '+254733959383',
    whatsapp: '+254733959383',
    services: ['Battery Swap', 'Repairs', 'Diagnostics'],
    hours: 'Mon-Sat: 8AM-6PM',
    mapLink: 'https://maps.google.com',
    batterySwapping: true,
    isActive: true,
  },
  {
    _id: 'hero-home',
    _type: 'heroSection',
    page: 'home',
    title: 'Spares at Your Doorstep',
    subtitle: 'Fast-moving parts, bikes, and service support for EV riders.',
    ctaText: 'Shop Now',
    ctaLink: '/spares',
  },
  {
    _id: 'page-home',
    _type: 'page',
    title: 'Home',
    slug: {current: 'home'},
    content: [
      {
        _type: 'block',
        _key: 'home-intro',
        style: 'normal',
        children: [{_type: 'span', _key: 'span-1', text: 'Welcome to Spiro Spares.'}],
      },
    ],
    seoTitle: 'Spiro Spares Home',
    seoDescription: 'Explore bikes, spares, gadgets, and service locations.',
    isPublished: true,
  },
]